//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.VSIX.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.VSIX.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Extension {
            get {
                object obj = ResourceManager.GetObject("Extension", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add switches and parameters to the Yeoman Generator commands..
        /// </summary>
        internal static string Form_AdvancedTab_CommandDescription {
            get {
                return ResourceManager.GetString("Form_AdvancedTab_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Form_AdvancedTab_Title {
            get {
                return ResourceManager.GetString("Form_AdvancedTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Form_ButtonCancel {
            get {
                return ResourceManager.GetString("Form_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Form_ButtonClose {
            get {
                return ResourceManager.GetString("Form_ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Form_ButtonGenerate {
            get {
                return ResourceManager.GetString("Form_ButtonGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command String:.
        /// </summary>
        internal static string Form_CommandString {
            get {
                return ResourceManager.GetString("Form_CommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Description:.
        /// </summary>
        internal static string Form_ComponentDescription {
            get {
                return ResourceManager.GetString("Form_ComponentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Name:.
        /// </summary>
        internal static string Form_ComponentName {
            get {
                return ResourceManager.GetString("Form_ComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required fields are empty..
        /// </summary>
        internal static string Form_EmptyFieldMessage {
            get {
                return ResourceManager.GetString("Form_EmptyFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Running the generator may take some time. Please wait while the process completes..
        /// </summary>
        internal static string Form_Footer_GeneratorText {
            get {
                return ResourceManager.GetString("Form_Footer_GeneratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework:.
        /// </summary>
        internal static string Form_Framework {
            get {
                return ResourceManager.GetString("Form_Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Framework Web Part Configuration.
        /// </summary>
        internal static string Form_Item_Name {
            get {
                return ResourceManager.GetString("Form_Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Framework Web Part Configuration.
        /// </summary>
        internal static string Form_Item_Title {
            get {
                return ResourceManager.GetString("Form_Item_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Form_LogTab_Title {
            get {
                return ResourceManager.GetString("Form_LogTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Framework Project Configuration.
        /// </summary>
        internal static string Form_Project_Name {
            get {
                return ResourceManager.GetString("Form_Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Framework Project Configuration.
        /// </summary>
        internal static string Form_Project_Title {
            get {
                return ResourceManager.GetString("Form_Project_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Form_PropertyTab_Title {
            get {
                return ResourceManager.GetString("Form_PropertyTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show command window.
        /// </summary>
        internal static string Form_ShowCommandWIndow {
            get {
                return ResourceManager.GetString("Form_ShowCommandWIndow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not automatically install dependencies (skip &quot;npm install&quot; command).
        /// </summary>
        internal static string Form_SkipInstall {
            get {
                return ResourceManager.GetString("Form_SkipInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --skip-install.
        /// </summary>
        internal static string Form_SkipInstall_Flag {
            get {
                return ResourceManager.GetString("Form_SkipInstall_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Name:.
        /// </summary>
        internal static string Form_SolutionName {
            get {
                return ResourceManager.GetString("Form_SolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --componentName &quot;{0}&quot; --componentDescription &quot;{1}&quot; --componentType &quot;{2}&quot;.
        /// </summary>
        internal static string Yeoman_Item_CommandString {
            get {
                return ResourceManager.GetString("Yeoman_Item_CommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --solutionName &quot;{0}&quot;  --framework &quot;{1}&quot; --componentName &quot;{2}&quot; --componentDescription &quot;{3}&quot; --componentType &quot;{4}&quot; {5}.
        /// </summary>
        internal static string Yeoman_Project_CommandString {
            get {
                return ResourceManager.GetString("Yeoman_Project_CommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --solutionName &quot;{0}&quot;  --framework &quot;{1}&quot; --componentName &quot;{2}&quot; --componentDescription &quot;{3}&quot; --componentType &quot;{4}&quot; {5}.
        /// </summary>
        internal static string Yeoman_Project_DefaultCommandString {
            get {
                return ResourceManager.GetString("Yeoman_Project_DefaultCommandString", resourceCulture);
            }
        }
    }
}
