//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.VSIX.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.VSIX.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Extension {
            get {
                object obj = ResourceManager.GetObject("Extension", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires version 1.8 of the SharePoint Framework Yeoman Generator.
        /// </summary>
        internal static string Footer_Yeoman_Version {
            get {
                return ResourceManager.GetString("Footer_Yeoman_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add switches and parameters to the Yeoman Generator commands..
        /// </summary>
        internal static string Form_AdvancedTab_CommandDescription {
            get {
                return ResourceManager.GetString("Form_AdvancedTab_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Form_AdvancedTab_Title {
            get {
                return ResourceManager.GetString("Form_AdvancedTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Form_ButtonCancel {
            get {
                return ResourceManager.GetString("Form_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Form_ButtonClose {
            get {
                return ResourceManager.GetString("Form_ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Form_ButtonGenerate {
            get {
                return ResourceManager.GetString("Form_ButtonGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command String:.
        /// </summary>
        internal static string Form_CommandString {
            get {
                return ResourceManager.GetString("Form_CommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Description:.
        /// </summary>
        internal static string Form_ComponentDescription {
            get {
                return ResourceManager.GetString("Form_ComponentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Name:.
        /// </summary>
        internal static string Form_ComponentName {
            get {
                return ResourceManager.GetString("Form_ComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentType:.
        /// </summary>
        internal static string Form_ComponentType {
            get {
                return ResourceManager.GetString("Form_ComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required fields are empty..
        /// </summary>
        internal static string Form_EmptyFieldMessage {
            get {
                return ResourceManager.GetString("Form_EmptyFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment:.
        /// </summary>
        internal static string Form_Environment {
            get {
                return ResourceManager.GetString("Form_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Type:.
        /// </summary>
        internal static string Form_ExtensionType {
            get {
                return ResourceManager.GetString("Form_ExtensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: If you don&apos;t skip &apos;npm install&apos;, running the generator may take several minutes. Please wait until it completes..
        /// </summary>
        internal static string Form_Footer_GeneratorText {
            get {
                return ResourceManager.GetString("Form_Footer_GeneratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework:.
        /// </summary>
        internal static string Form_Framework {
            get {
                return ResourceManager.GetString("Form_Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Framework Web Part Configuration.
        /// </summary>
        internal static string Form_Item_Name {
            get {
                return ResourceManager.GetString("Form_Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Framework Web Part Configuration.
        /// </summary>
        internal static string Form_Item_Title {
            get {
                return ResourceManager.GetString("Form_Item_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: If this option is unchecked, the generator will insert a string value of &quot;false&quot; into the package-soluiton.json file. You must change it manually to a boolean false value or the build task will fail..
        /// </summary>
        internal static string Form_Label_IsDomainIsolated_Info {
            get {
                return ResourceManager.GetString("Form_Label_IsDomainIsolated_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: If this option is unchecked, the generator will insert a string value of &quot;false&quot; into the package-soluiton.json file. You must change it manually to a boolean false value or the build task will fail..
        /// </summary>
        internal static string Form_Label_SkipFeatureDeployment_Info {
            get {
                return ResourceManager.GetString("Form_Label_SkipFeatureDeployment_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Form_LogTab_Title {
            get {
                return ResourceManager.GetString("Form_LogTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Beta Features.
        /// </summary>
        internal static string Form_PlusBeta {
            get {
                return ResourceManager.GetString("Form_PlusBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Framework Project Configuration.
        /// </summary>
        internal static string Form_Project_Name {
            get {
                return ResourceManager.GetString("Form_Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Framework Project Configuration.
        /// </summary>
        internal static string Form_Project_Title {
            get {
                return ResourceManager.GetString("Form_Project_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string Form_Prompt_ComponentType_Extension {
            get {
                return ResourceManager.GetString("Form_Prompt_ComponentType_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Customizer.
        /// </summary>
        internal static string Form_Prompt_ComponentType_Extension_1 {
            get {
                return ResourceManager.GetString("Form_Prompt_ComponentType_Extension_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Customizer.
        /// </summary>
        internal static string Form_Prompt_ComponentType_Extension_2 {
            get {
                return ResourceManager.GetString("Form_Prompt_ComponentType_Extension_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Set.
        /// </summary>
        internal static string Form_Prompt_ComponentType_Extension_3 {
            get {
                return ResourceManager.GetString("Form_Prompt_ComponentType_Extension_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Part.
        /// </summary>
        internal static string Form_Prompt_ComponentType_WebPart {
            get {
                return ResourceManager.GetString("Form_Prompt_ComponentType_WebPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components require permissions to access web API&apos;s that are unique and not shared with other components in the tenant?.
        /// </summary>
        internal static string Form_Prompt_Domain_Isolated_Label {
            get {
                return ResourceManager.GetString("Form_Prompt_Domain_Isolated_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline Packages.
        /// </summary>
        internal static string Form_Prompt_Environment_Label {
            get {
                return ResourceManager.GetString("Form_Prompt_Environment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Online only (latest).
        /// </summary>
        internal static string Form_Prompt_Environment_Option1 {
            get {
                return ResourceManager.GetString("Form_Prompt_Environment_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2016 onwards, including 2018 and SharePoint Online.
        /// </summary>
        internal static string Form_Prompt_Environment_Option2 {
            get {
                return ResourceManager.GetString("Form_Prompt_Environment_Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2019 onwards, including SharePoint Online.
        /// </summary>
        internal static string Form_Prompt_Environment_Option3 {
            get {
                return ResourceManager.GetString("Form_Prompt_Environment_Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Manager:.
        /// </summary>
        internal static string Form_Prompt_PackageManager_Label {
            get {
                return ResourceManager.GetString("Form_Prompt_PackageManager_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include preview (beta) features?.
        /// </summary>
        internal static string Form_Prompt_PlusBeta_Label {
            get {
                return ResourceManager.GetString("Form_Prompt_PlusBeta_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip feature deployment?.
        /// </summary>
        internal static string Form_Prompt_SkipFeature_Label {
            get {
                return ResourceManager.GetString("Form_Prompt_SkipFeature_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip running &quot;npm install&quot; command?.
        /// </summary>
        internal static string Form_Prompt_SkipInstall_Label {
            get {
                return ResourceManager.GetString("Form_Prompt_SkipInstall_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Form_PropertyTab_Title {
            get {
                return ResourceManager.GetString("Form_PropertyTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show command window (if checked, manually exit from command window when execution is completed).
        /// </summary>
        internal static string Form_ShowCommandWindow {
            get {
                return ResourceManager.GetString("Form_ShowCommandWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Feature Deployment.
        /// </summary>
        internal static string Form_SkipFeatureDeployment {
            get {
                return ResourceManager.GetString("Form_SkipFeatureDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not automatically install dependencies (skip &quot;npm install&quot; command).
        /// </summary>
        internal static string Form_SkipInstall {
            get {
                return ResourceManager.GetString("Form_SkipInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --skip-install.
        /// </summary>
        internal static string Form_SkipInstall_Flag {
            get {
                return ResourceManager.GetString("Form_SkipInstall_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Name:.
        /// </summary>
        internal static string Form_SolutionName {
            get {
                return ResourceManager.GetString("Form_SolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1.0.
        /// </summary>
        internal static string Yeoman_Generator_ExtensionsVersion {
            get {
                return ResourceManager.GetString("Yeoman_Generator_ExtensionsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to npm list @microsoft/generator-sharepoint -g -json.
        /// </summary>
        internal static string Yeoman_Generator_VersionCheck {
            get {
                return ResourceManager.GetString("Yeoman_Generator_VersionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --component-name &quot;{0}&quot; --component-description &quot;{1}&quot;.
        /// </summary>
        internal static string Yeoman_Item_CommandString {
            get {
                return ResourceManager.GetString("Yeoman_Item_CommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --component-name &quot;{0}&quot; --component-description &quot;{1}&quot; --framework &quot;{2}&quot; --component-type &quot;webpart&quot;.
        /// </summary>
        internal static string Yeoman_Item_CommandString_Extensions {
            get {
                return ResourceManager.GetString("Yeoman_Item_CommandString_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --solutionName &quot;{0}&quot;  --framework &quot;{1}&quot; --component-name &quot;{2}&quot; --component-description &quot;{3}&quot; {4}.
        /// </summary>
        internal static string Yeoman_Project_CommandString {
            get {
                return ResourceManager.GetString("Yeoman_Project_CommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --solutionName &quot;{0}&quot;  --framework &quot;{1}&quot; --component-name &quot;{2}&quot; --component-description &quot;{3}&quot; {4}.
        /// </summary>
        internal static string Yeoman_Project_CommandString_1_0 {
            get {
                return ResourceManager.GetString("Yeoman_Project_CommandString_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --solutionName &quot;{0}&quot;  --framework &quot;{1}&quot; --component-name &quot;{2}&quot; --component-description &quot;{3}&quot; --component-type &quot;webpart&quot; {4}.
        /// </summary>
        internal static string Yeoman_Project_CommandString_1_1 {
            get {
                return ResourceManager.GetString("Yeoman_Project_CommandString_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --solutionName &quot;{0}&quot;  --framework &quot;{1}&quot; --component-name &quot;{2}&quot; --component-description &quot;{3}&quot; --component-type &quot;{5}&quot; {4}.
        /// </summary>
        internal static string Yeoman_Project_CommandString_1_3 {
            get {
                return ResourceManager.GetString("Yeoman_Project_CommandString_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --solution-Name &quot;{0}&quot;  --framework &quot;{1}&quot; --component-name &quot;{2}&quot; --component-description &quot;{3}&quot; --component-type &quot;{4}&quot; --environment &quot;{5}&quot; --package-manager &quot;{6}&quot; --is-domain-isolated &quot;{7}&quot; --skip-cache &quot;true&quot; {8}.
        /// </summary>
        internal static string Yeoman_Project_CommandString_1_7 {
            get {
                return ResourceManager.GetString("Yeoman_Project_CommandString_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --solutionName &quot;{0}&quot;  --framework &quot;{1}&quot; --componentName &quot;{2}&quot; --componentDescription &quot;{3}&quot; --componentType &quot;webpart&quot; {4}.
        /// </summary>
        internal static string Yeoman_Project_CommandString_Extensions {
            get {
                return ResourceManager.GetString("Yeoman_Project_CommandString_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo @microsoft/sharepoint --solutionName &quot;{0}&quot;  --framework &quot;{1}&quot; --componentName &quot;{2}&quot; --componentDescription &quot;{3}&quot;{4}.
        /// </summary>
        internal static string Yeoman_Project_DefaultCommandString {
            get {
                return ResourceManager.GetString("Yeoman_Project_DefaultCommandString", resourceCulture);
            }
        }
    }
}
